#https://projecteuler.net/problem=2

'''
Each new term in the Fibonacci sequence is generated by adding 
the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.
'''

#get Fibonacci list and stop if the number is greater than 4.000.000
#we need to break otherwise the list comprehension in the main() will loop forever
def calc_fibo():
  a, b = 0, 1
  while True:
    if a > 4000000:
      break
    yield a
    a, b = b, a + b


print(sum([x for x in calc_fibo() if x % 2 == 0]))
