# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
total = 0
curr, nextval = 1,2
def fib(i):
    if i < 2:
        return i
    else:
        return(fib(i-1) + fib(i-2))
sequence=0
term=0
output_sum=0
while sequence < 4000000:
    sequence=fib(term)
    print(sequence)
    term = term+1
    if sequence % 2 == 0 & sequence < 4000000:
        output_sum = output_sum+sequence

print("The answer is {}".format(output_sum))
    