# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ChallengePipeline

on:
  push:
    branches: [ wip, master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run mypy
      run: |
        # running mypy for type checking
        mypy .
    - name: Test with pytest
      run: |
        pytest
    - name: Run Challenge 2
      run: |
        echo '+++++++++++++++++++++'
        python damir2/p02.py
        echo '+++++++++++++++++++++'
        python damir2/p54.py
    - name: Run Challenge 3
      run: |
        echo '+++++++++++++++++++++'
        python damir3/p041.py
        echo '+++++++++++++++++++++'
        python damir3/p059.py
